// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooSanMarino.Infrastructure.Persistence;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    [DbContext(typeof(ZooSanMarinoContext))]
    [Migration("20250901200628_Initial_Aligned")]
    partial class Initial_Aligned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_catalogo_items");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_catalogo_items_activo");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_catalogo_items_codigo");

                    b.HasIndex("Nombre")
                        .HasDatabaseName("ix_catalogo_items_nombre");

                    b.ToTable("catalogo_items", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("country");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("identifier");

                    b.Property<bool>("MobileAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("mobile_access");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("state");

                    b.PrimitiveCollection<string[]>("VisualPermissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("visual_permissions");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("DepartamentoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("departamento_nombre");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer")
                        .HasColumnName("pais_id");

                    b.HasKey("DepartamentoId")
                        .HasName("pk_departamento");

                    b.HasIndex("PaisId")
                        .HasDatabaseName("ix_departamentos_pais_id");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int>("RegionalId")
                        .HasColumnType("integer")
                        .HasColumnName("regional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue("A")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_farms_company_id");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Galpon", b =>
                {
                    b.Property<string>("GalponId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_id");

                    b.Property<string>("Ancho")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ancho");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("GalponNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("galpon_nombre");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<string>("Largo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("largo");

                    b.Property<string>("NucleoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nucleo_id");

                    b.Property<string>("TipoGalpon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_galpon");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("GalponId")
                        .HasName("pk_galpones");

                    b.HasIndex("GranjaId")
                        .HasDatabaseName("ix_galpones_granja_id");

                    b.HasIndex("NucleoId", "GranjaId")
                        .HasDatabaseName("ix_galpones_nucleo_id_granja_id");

                    b.ToTable("galpones", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEmailLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_email_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_logins");

                    b.ToTable("logins", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Lote", b =>
                {
                    b.Property<string>("LoteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int?>("AnoTablaGenetica")
                        .HasColumnType("integer")
                        .HasColumnName("ano_tabla_genetica");

                    b.Property<int?>("AvesEncasetadas")
                        .HasColumnType("integer")
                        .HasColumnName("aves_encasetadas");

                    b.Property<string>("CodigoGuiaGenetica")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo_guia_genetica");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("EdadInicial")
                        .HasColumnType("integer")
                        .HasColumnName("edad_inicial");

                    b.Property<DateTime?>("FechaEncaset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_encaset");

                    b.Property<string>("GalponId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_id");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<int?>("HembrasL")
                        .HasColumnType("integer")
                        .HasColumnName("hembras_l");

                    b.Property<string>("Linea")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("linea");

                    b.Property<string>("LoteNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("lote_nombre");

                    b.Property<int?>("MachosL")
                        .HasColumnType("integer")
                        .HasColumnName("machos_l");

                    b.Property<int?>("Mixtas")
                        .HasColumnType("integer")
                        .HasColumnName("mixtas");

                    b.Property<int?>("MortCajaH")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_h");

                    b.Property<int?>("MortCajaM")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_m");

                    b.Property<string>("NucleoId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nucleo_id");

                    b.Property<double?>("PesoInicialH")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_inicial_h");

                    b.Property<double?>("PesoInicialM")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_inicial_m");

                    b.Property<double?>("PesoMixto")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_mixto");

                    b.Property<string>("Raza")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("raza");

                    b.Property<string>("Regional")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("regional");

                    b.Property<string>("Tecnico")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("tecnico");

                    b.Property<string>("TipoLinea")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("tipo_linea");

                    b.Property<double?>("UnifH")
                        .HasColumnType("double precision")
                        .HasColumnName("unif_h");

                    b.Property<double?>("UnifM")
                        .HasColumnType("double precision")
                        .HasColumnName("unif_m");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("LoteId")
                        .HasName("pk_lotes");

                    b.HasIndex("GalponId")
                        .HasDatabaseName("ix_lotes_galpon_id");

                    b.HasIndex("GranjaId")
                        .HasDatabaseName("ix_lotes_granja_id");

                    b.HasIndex("NucleoId", "GranjaId")
                        .HasDatabaseName("ix_lotes_nucleo_id_granja_id");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteGalpon", b =>
                {
                    b.Property<string>("LoteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<string>("ReproductoraId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reproductora_id");

                    b.Property<string>("GalponId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_id");

                    b.Property<int?>("H")
                        .HasColumnType("integer")
                        .HasColumnName("hembra");

                    b.Property<int?>("M")
                        .HasColumnType("integer")
                        .HasColumnName("macho");

                    b.HasKey("LoteId", "ReproductoraId", "GalponId")
                        .HasName("pk_lote_galpones");

                    b.HasIndex("GalponId")
                        .HasDatabaseName("ix_lote_galpones_galpon_id");

                    b.ToTable("lote_galpones", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteReproductora", b =>
                {
                    b.Property<string>("LoteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<string>("ReproductoraId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reproductora_id");

                    b.Property<DateTime?>("FechaEncasetamiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_encasetamiento");

                    b.Property<int?>("H")
                        .HasColumnType("integer")
                        .HasColumnName("h");

                    b.Property<int?>("M")
                        .HasColumnType("integer")
                        .HasColumnName("m");

                    b.Property<int?>("Mixtas")
                        .HasColumnType("integer")
                        .HasColumnName("mixtas");

                    b.Property<int?>("MortCajaH")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_h");

                    b.Property<int?>("MortCajaM")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_m");

                    b.Property<string>("NombreLote")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_lote");

                    b.Property<decimal?>("PesoInicialH")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("peso_inicial_h");

                    b.Property<decimal?>("PesoInicialM")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("peso_inicial_m");

                    b.Property<decimal?>("PesoMixto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("peso_mixto");

                    b.Property<int?>("UnifH")
                        .HasColumnType("integer")
                        .HasColumnName("unif_h");

                    b.Property<int?>("UnifM")
                        .HasColumnType("integer")
                        .HasColumnName("unif_m");

                    b.HasKey("LoteId", "ReproductoraId")
                        .HasName("pk_lote_reproductoras");

                    b.ToTable("lote_reproductoras", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteSeguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<decimal?>("ConsumoAlimento")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("consumo_alimento");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("ErrorH")
                        .HasColumnType("integer")
                        .HasColumnName("error_h");

                    b.Property<int?>("ErrorM")
                        .HasColumnType("integer")
                        .HasColumnName("error_m");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int?>("MortalidadH")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_h");

                    b.Property<int?>("MortalidadM")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_m");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PesoFinal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("peso_final");

                    b.Property<decimal?>("PesoInicial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("peso_inicial");

                    b.Property<string>("ReproductoraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reproductora_id");

                    b.Property<int?>("SelH")
                        .HasColumnType("integer")
                        .HasColumnName("sel_h");

                    b.Property<int?>("SelM")
                        .HasColumnType("integer")
                        .HasColumnName("sel_m");

                    b.Property<string>("TipoAlimento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_alimento");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_lote_seguimientos");

                    b.HasIndex("LoteId", "ReproductoraId")
                        .HasDatabaseName("ix_lote_seguimientos_lote_id_reproductora_id");

                    b.ToTable("lote_seguimientos", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_master_lists");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_master_lists_key");

                    b.ToTable("master_lists", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterListOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterListId")
                        .HasColumnType("integer")
                        .HasColumnName("master_list_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_master_list_options");

                    b.HasIndex("MasterListId")
                        .HasDatabaseName("ix_master_list_options_master_list_id");

                    b.ToTable("master_list_options", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("Route")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route");

                    b.HasKey("Id")
                        .HasName("pk_menus");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_menus_parent_id");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MenuPermission", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("MenuId", "PermissionId")
                        .HasName("pk_menu_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_menu_permissions_permission_id");

                    b.ToTable("menu_permissions", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MunicipioId"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.Property<string>("MunicipioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("municipio_nombre");

                    b.HasKey("MunicipioId")
                        .HasName("pk_municipio");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("ix_municipios_departamento_id");

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Nucleo", b =>
                {
                    b.Property<string>("NucleoId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nucleo_id");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("NucleoNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nucleo_nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("NucleoId", "GranjaId")
                        .HasName("pk_nucleos");

                    b.HasIndex("GranjaId")
                        .HasDatabaseName("ix_nucleos_granja_id");

                    b.ToTable("nucleos", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pais_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaisId"));

                    b.Property<string>("PaisNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pais_nombre");

                    b.HasKey("PaisId")
                        .HasName("pk_paises");

                    b.ToTable("paises", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_key");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.PlanGramajeGalpon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("GalponId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_id");

                    b.Property<double>("GramajeGrPorAve")
                        .HasPrecision(12, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("gramaje_gr_por_ave");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<int>("SemanaDesde")
                        .HasColumnType("integer")
                        .HasColumnName("semana_desde");

                    b.Property<int>("SemanaHasta")
                        .HasColumnType("integer")
                        .HasColumnName("semana_hasta");

                    b.Property<string>("TipoAlimento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_alimento");

                    b.Property<bool>("Vigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id")
                        .HasName("pk_plan_gramaje_galpon");

                    b.HasIndex("GalponId")
                        .HasDatabaseName("ix_plan_gramaje_galpon_galpon_id");

                    b.ToTable("plan_gramaje_galpon", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsKgH")
                        .HasColumnType("double precision")
                        .HasColumnName("cons_kg_h");

                    b.Property<double>("ConsKgM")
                        .HasColumnType("double precision")
                        .HasColumnName("cons_kg_m");

                    b.Property<int>("Etapa")
                        .HasColumnType("integer")
                        .HasColumnName("etapa");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("HuevoInc")
                        .HasColumnType("integer")
                        .HasColumnName("huevo_inc");

                    b.Property<int>("HuevoTot")
                        .HasColumnType("integer")
                        .HasColumnName("huevo_tot");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lote_id");

                    b.Property<int?>("LoteProduccionId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_produccion_id");

                    b.Property<int>("MortalidadHembras")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_hembras");

                    b.Property<int>("MortalidadMachos")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_machos");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<double?>("PesoHuevo")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_huevo");

                    b.Property<int>("SelH")
                        .HasColumnType("integer")
                        .HasColumnName("sel_h");

                    b.Property<string>("TipoAlimento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_alimento");

                    b.HasKey("Id")
                        .HasName("pk_produccion_diaria");

                    b.HasIndex("LoteProduccionId")
                        .HasDatabaseName("ix_produccion_diaria_lote_produccion_id");

                    b.ToTable("produccion_diaria", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Normal")
                        .HasColumnName("ciclo");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("FechaInicioProduccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_produccion");

                    b.Property<string>("GalponId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_id");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<int>("HembrasIniciales")
                        .HasColumnType("integer")
                        .HasColumnName("hembras_iniciales");

                    b.Property<int>("HuevosIniciales")
                        .HasColumnType("integer")
                        .HasColumnName("huevos_iniciales");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int>("MachosIniciales")
                        .HasColumnType("integer")
                        .HasColumnName("machos_iniciales");

                    b.Property<string>("NucleoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nucleo_id");

                    b.Property<string>("TipoNido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_nido");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_produccion_lotes");

                    b.HasIndex("GalponId")
                        .HasDatabaseName("ix_produccion_lotes_galpon_id");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_produccion_lotes_lote_id");

                    b.HasIndex("NucleoId", "GranjaId")
                        .HasDatabaseName("ix_produccion_lotes_nucleo_id_granja_id");

                    b.ToTable("produccion_lotes", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Regional", b =>
                {
                    b.Property<int>("RegionalCia")
                        .HasColumnType("integer")
                        .HasColumnName("regional_cia");

                    b.Property<int>("RegionalId")
                        .HasColumnType("integer")
                        .HasColumnName("regional_id");

                    b.Property<string>("RegionalCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("regional_codigo");

                    b.Property<string>("RegionalEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("regional_estado");

                    b.Property<string>("RegionalNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("regional_nombre");

                    b.HasKey("RegionalCia", "RegionalId")
                        .HasName("pk_regionales");

                    b.ToTable("regionales", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.RoleCompany", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.HasKey("RoleId", "CompanyId")
                        .HasName("pk_role_companies");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_role_companies_company_id");

                    b.ToTable("role_companies", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.SeguimientoLoteLevante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Normal")
                        .HasColumnName("ciclo");

                    b.Property<double>("ConsumoKgHembras")
                        .HasPrecision(12, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("consumo_kg_hembras");

                    b.Property<int>("ErrorSexajeHembras")
                        .HasColumnType("integer")
                        .HasColumnName("error_sexaje_hembras");

                    b.Property<int>("ErrorSexajeMachos")
                        .HasColumnType("integer")
                        .HasColumnName("error_sexaje_machos");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<double?>("KcalAlH")
                        .HasPrecision(12, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("kcal_al_h");

                    b.Property<double?>("KcalAveH")
                        .HasPrecision(12, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("kcal_ave_h");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int>("MortalidadHembras")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_hembras");

                    b.Property<int>("MortalidadMachos")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_machos");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observaciones");

                    b.Property<double?>("ProtAlH")
                        .HasPrecision(12, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("prot_al_h");

                    b.Property<double?>("ProtAveH")
                        .HasPrecision(12, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("prot_ave_h");

                    b.Property<int>("SelH")
                        .HasColumnType("integer")
                        .HasColumnName("sel_h");

                    b.Property<int>("SelM")
                        .HasColumnType("integer")
                        .HasColumnName("sel_m");

                    b.Property<string>("TipoAlimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_alimento");

                    b.HasKey("Id")
                        .HasName("pk_seguimiento_lote_levante");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_seguimiento_lote_levante_lote_id");

                    b.ToTable("seguimiento_lote_levante", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cedula");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("surName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sur_name");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.UserCompany", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.HasKey("UserId", "CompanyId")
                        .HasName("pk_user_companies");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_user_companies_company_id");

                    b.ToTable("user_companies", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.UserLogin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("LoginId")
                        .HasColumnType("uuid")
                        .HasColumnName("login_id");

                    b.Property<bool>("IsLockedByAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked_by_admin");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lock_reason");

                    b.HasKey("UserId", "LoginId")
                        .HasName("pk_user_logins");

                    b.HasIndex("LoginId")
                        .HasDatabaseName("ix_user_logins_login_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_user_roles_company_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Zona", b =>
                {
                    b.Property<int>("ZonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZonaId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<int>("ZonaCia")
                        .HasColumnType("integer")
                        .HasColumnName("zona_cia");

                    b.Property<string>("ZonaEstado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zona_estado");

                    b.Property<string>("ZonaNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zona_nombre");

                    b.HasKey("ZonaId")
                        .HasName("pk_zonas");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_zonas_company_id");

                    b.ToTable("zonas", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Pais", "Pais")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departamentos_paises_pais_id");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Farm", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("Farms")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_farms_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Galpon", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Farm", "Farm")
                        .WithMany("Galpones")
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_galpones_farms_granja_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Nucleo", "Nucleo")
                        .WithMany("Galpones")
                        .HasForeignKey("NucleoId", "GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_galpones_nucleos_nucleo_id_granja_id");

                    b.Navigation("Farm");

                    b.Navigation("Nucleo");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Lote", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Galpon", "Galpon")
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lotes_galpones_galpon_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Farm", "Farm")
                        .WithMany("Lotes")
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_farms_granja_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Nucleo", "Nucleo")
                        .WithMany("Lotes")
                        .HasForeignKey("NucleoId", "GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lotes_nucleos_nucleo_id_granja_id");

                    b.Navigation("Farm");

                    b.Navigation("Galpon");

                    b.Navigation("Nucleo");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteGalpon", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Galpon", "Galpon")
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lote_galpones_galpones_galpon_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.LoteReproductora", "LoteReproductora")
                        .WithMany("LoteGalpones")
                        .HasForeignKey("LoteId", "ReproductoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_galpones_lote_reproductoras_lote_id_reproductora_id");

                    b.Navigation("Galpon");

                    b.Navigation("LoteReproductora");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteReproductora", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Lote", "Lote")
                        .WithMany("Reproductoras")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_reproductoras_lotes_lote_id");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteSeguimiento", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lote_seguimientos_lotes_lote_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.LoteReproductora", "LoteReproductora")
                        .WithMany("LoteSeguimientos")
                        .HasForeignKey("LoteId", "ReproductoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_seguimientos_lote_reproductoras_lote_id_reproductora_id");

                    b.Navigation("Lote");

                    b.Navigation("LoteReproductora");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterListOption", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.MasterList", "MasterList")
                        .WithMany("Options")
                        .HasForeignKey("MasterListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_list_options_master_lists_master_list_id");

                    b.Navigation("MasterList");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Menu", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_menus_menus_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MenuPermission", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Menu", "Menu")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_permissions_menus_menu_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Permission", "Permission")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_permissions_permissions_permission_id");

                    b.Navigation("Menu");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipios_departamentos_departamento_id");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Nucleo", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Farm", "Farm")
                        .WithMany("Nucleos")
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nucleos_farms_granja_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.PlanGramajeGalpon", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Galpon", null)
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_gramaje_galpon_galpones_galpon_id");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionDiaria", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.ProduccionLote", "LoteProduccion")
                        .WithMany()
                        .HasForeignKey("LoteProduccionId")
                        .HasConstraintName("fk_produccion_diaria_produccion_lotes_lote_produccion_id");

                    b.Navigation("LoteProduccion");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionLote", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Galpon", "Galpon")
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_produccion_lotes_galpones_galpon_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produccion_lotes_lotes_lote_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Nucleo", "Nucleo")
                        .WithMany()
                        .HasForeignKey("NucleoId", "GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produccion_lotes_nucleos_nucleo_id_granja_id");

                    b.Navigation("Galpon");

                    b.Navigation("Lote");

                    b.Navigation("Nucleo");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Regional", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("Regionales")
                        .HasForeignKey("RegionalCia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regionales_companies_regional_cia");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.RoleCompany", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("RoleCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_companies_companies_company_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Role", "Role")
                        .WithMany("RoleCompanies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_companies_roles_role_id");

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.SeguimientoLoteLevante", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seguimiento_lote_levante_lotes_lote_id");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.UserCompany", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("UserCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_companies_companies_company_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.User", "User")
                        .WithMany("UserCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_companies_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Login", "Login")
                        .WithMany("UserLogins")
                        .HasForeignKey("LoginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_logins_login_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.User", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");

                    b.Navigation("Login");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_companies_company_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Zona", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("Zonas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zonas_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Company", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Regionales");

                    b.Navigation("RoleCompanies");

                    b.Navigation("UserCompanies");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Galpones");

                    b.Navigation("Lotes");

                    b.Navigation("Nucleos");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Login", b =>
                {
                    b.Navigation("UserLogins");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Lote", b =>
                {
                    b.Navigation("Reproductoras");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteReproductora", b =>
                {
                    b.Navigation("LoteGalpones");

                    b.Navigation("LoteSeguimientos");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterList", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Nucleo", b =>
                {
                    b.Navigation("Galpones");

                    b.Navigation("Lotes");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Pais", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Permission", b =>
                {
                    b.Navigation("MenuPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleCompanies");

                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.User", b =>
                {
                    b.Navigation("UserCompanies");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
