// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooSanMarino.Infrastructure.Persistence;

#nullable disable

namespace ZooSanMarino.Infrastructure.Migrations
{
    [DbContext(typeof(ZooSanMarinoContext))]
    [Migration("20250624002526_AddCamposGalponExtendido")]
    partial class AddCamposGalponExtendido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<bool>("MobileAccess")
                        .HasColumnType("boolean")
                        .HasColumnName("mobile_access");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.PrimitiveCollection<string[]>("VisualPermissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("visual_permissions");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartamentoId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("DepartamentoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("departamento_nombre");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer")
                        .HasColumnName("pais_id");

                    b.HasKey("DepartamentoId")
                        .HasName("pk_departamento");

                    b.HasIndex("PaisId")
                        .HasDatabaseName("ix_departamentos_pais_id");

                    b.ToTable("departamentos", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("RegionalId")
                        .HasColumnType("integer")
                        .HasColumnName("regional_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_farms");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_farms_company_id");

                    b.ToTable("farms", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Galpon", b =>
                {
                    b.Property<string>("GalponId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_id");

                    b.Property<string>("Ancho")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ancho");

                    b.Property<string>("GalponNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("galpon_nombre");

                    b.Property<string>("GalponNucleoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_nucleo_id");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<string>("Largo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("largo");

                    b.Property<string>("TipoGalpon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_galpon");

                    b.HasKey("GalponId")
                        .HasName("pk_galpones");

                    b.HasIndex("GranjaId")
                        .HasDatabaseName("ix_galpones_granja_id");

                    b.HasIndex("GalponNucleoId", "GranjaId")
                        .HasDatabaseName("ix_galpones_galpon_nucleo_id_granja_id");

                    b.ToTable("galpones", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Lote", b =>
                {
                    b.Property<string>("LoteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int?>("AnoTablaGenetica")
                        .HasColumnType("integer")
                        .HasColumnName("ano_tabla_genetica");

                    b.Property<string>("CodigoGuiaGenetica")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_guia_genetica");

                    b.Property<DateTime?>("FechaEncaset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_encaset");

                    b.Property<int?>("GalponId")
                        .HasColumnType("integer")
                        .HasColumnName("galpon_id");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<int?>("HembrasL")
                        .HasColumnType("integer")
                        .HasColumnName("hembras_l");

                    b.Property<string>("Linea")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("linea");

                    b.Property<string>("LoteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lote_nombre");

                    b.Property<int?>("MachosL")
                        .HasColumnType("integer")
                        .HasColumnName("machos_l");

                    b.Property<int?>("MortCajaH")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_h");

                    b.Property<int?>("MortCajaM")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_m");

                    b.Property<int?>("NucleoId")
                        .HasColumnType("integer")
                        .HasColumnName("nucleo_id");

                    b.Property<double?>("PesoInicialH")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_inicial_h");

                    b.Property<double?>("PesoInicialM")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_inicial_m");

                    b.Property<string>("Raza")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("raza");

                    b.Property<string>("Regional")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("regional");

                    b.Property<string>("Tecnico")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tecnico");

                    b.Property<string>("TipoLinea")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_linea");

                    b.Property<double?>("UnifH")
                        .HasColumnType("double precision")
                        .HasColumnName("unif_h");

                    b.Property<double?>("UnifM")
                        .HasColumnType("double precision")
                        .HasColumnName("unif_m");

                    b.HasKey("LoteId")
                        .HasName("pk_lotes");

                    b.HasIndex("GranjaId")
                        .HasDatabaseName("ix_lotes_granja_id");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteGalpon", b =>
                {
                    b.Property<string>("LoteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<string>("ReproductoraId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reproductora_id");

                    b.Property<string>("GalponId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("galpon_id");

                    b.Property<int?>("H")
                        .HasColumnType("integer")
                        .HasColumnName("hembra");

                    b.Property<int?>("M")
                        .HasColumnType("integer")
                        .HasColumnName("macho");

                    b.HasKey("LoteId", "ReproductoraId", "GalponId")
                        .HasName("pk_lote_galpones");

                    b.HasIndex("GalponId")
                        .HasDatabaseName("ix_lote_galpones_galpon_id");

                    b.ToTable("lote_galpones", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteReproductora", b =>
                {
                    b.Property<string>("LoteId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<string>("ReproductoraId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reproductora_id");

                    b.Property<DateTime?>("FechaEncasetamiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_encasetamiento");

                    b.Property<int?>("H")
                        .HasColumnType("integer")
                        .HasColumnName("hembra");

                    b.Property<int?>("M")
                        .HasColumnType("integer")
                        .HasColumnName("macho");

                    b.Property<int?>("MortCajaH")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_h");

                    b.Property<int?>("MortCajaM")
                        .HasColumnType("integer")
                        .HasColumnName("mort_caja_m");

                    b.Property<string>("NombreLote")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_lote");

                    b.Property<decimal?>("PesoInicialH")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_inicial_h");

                    b.Property<decimal?>("PesoInicialM")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_inicial_m");

                    b.Property<int?>("UnifH")
                        .HasColumnType("integer")
                        .HasColumnName("unif_h");

                    b.Property<int?>("UnifM")
                        .HasColumnType("integer")
                        .HasColumnName("unif_m");

                    b.HasKey("LoteId", "ReproductoraId")
                        .HasName("pk_lote_reproductoras");

                    b.ToTable("lote_reproductoras", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteSeguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ConsumoAlimento")
                        .HasColumnType("numeric")
                        .HasColumnName("consumo_alimento");

                    b.Property<int?>("ErrorH")
                        .HasColumnType("integer")
                        .HasColumnName("error_h");

                    b.Property<int?>("ErrorM")
                        .HasColumnType("integer")
                        .HasColumnName("error_m");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int?>("MortalidadH")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_h");

                    b.Property<int?>("MortalidadM")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_m");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PesoFinal")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_final");

                    b.Property<decimal?>("PesoInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_inicial");

                    b.Property<string>("ReproductoraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reproductora_id");

                    b.Property<int?>("SelH")
                        .HasColumnType("integer")
                        .HasColumnName("sel_h");

                    b.Property<int?>("SelM")
                        .HasColumnType("integer")
                        .HasColumnName("sel_m");

                    b.Property<string>("TipoAlimento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_alimento");

                    b.HasKey("Id")
                        .HasName("pk_lote_seguimientos");

                    b.HasIndex("LoteId", "ReproductoraId")
                        .HasDatabaseName("ix_lote_seguimientos_lote_id_reproductora_id");

                    b.ToTable("lote_seguimientos", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_master_lists");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_master_lists_key");

                    b.ToTable("master_lists", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterListOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterListId")
                        .HasColumnType("integer")
                        .HasColumnName("master_list_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_master_list_options");

                    b.HasIndex("MasterListId")
                        .HasDatabaseName("ix_master_list_options_master_list_id");

                    b.ToTable("master_list_options", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("MunicipioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MunicipioId"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.Property<string>("MunicipioNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("municipio_nombre");

                    b.HasKey("MunicipioId")
                        .HasName("pk_municipio");

                    b.HasIndex("DepartamentoId")
                        .HasDatabaseName("ix_municipios_departamento_id");

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Nucleo", b =>
                {
                    b.Property<string>("NucleoId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nucleo_id");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<string>("NucleoNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nucleo_nombre");

                    b.HasKey("NucleoId", "GranjaId")
                        .HasName("pk_nucleos");

                    b.HasIndex("GranjaId")
                        .HasDatabaseName("ix_nucleos_granja_id");

                    b.ToTable("nucleos", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pais_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaisId"));

                    b.Property<string>("PaisNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pais_nombre");

                    b.HasKey("PaisId")
                        .HasName("pk_paises");

                    b.ToTable("paises", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsKgH")
                        .HasColumnType("double precision")
                        .HasColumnName("cons_kg_h");

                    b.Property<double>("ConsKgM")
                        .HasColumnType("double precision")
                        .HasColumnName("cons_kg_m");

                    b.Property<int>("Etapa")
                        .HasColumnType("integer")
                        .HasColumnName("etapa");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("HuevoInc")
                        .HasColumnType("integer")
                        .HasColumnName("huevo_inc");

                    b.Property<int>("HuevoTot")
                        .HasColumnType("integer")
                        .HasColumnName("huevo_tot");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lote_id");

                    b.Property<int?>("LoteProduccionId")
                        .HasColumnType("integer")
                        .HasColumnName("lote_produccion_id");

                    b.Property<int>("MortalidadHembras")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_hembras");

                    b.Property<int>("MortalidadMachos")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_machos");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<double?>("PesoHuevo")
                        .HasColumnType("double precision")
                        .HasColumnName("peso_huevo");

                    b.Property<int>("SelH")
                        .HasColumnType("integer")
                        .HasColumnName("sel_h");

                    b.Property<string>("TipoAlimento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_alimento");

                    b.HasKey("Id")
                        .HasName("pk_produccion_diaria");

                    b.HasIndex("LoteProduccionId")
                        .HasDatabaseName("ix_produccion_diaria_lote_produccion_id");

                    b.ToTable("produccion_diaria", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionLote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ciclo");

                    b.Property<DateTime>("FechaInicioProduccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("GranjaId")
                        .HasColumnType("integer")
                        .HasColumnName("granja_id");

                    b.Property<int>("HembrasIniciales")
                        .HasColumnType("integer")
                        .HasColumnName("hembras_iniciales");

                    b.Property<int>("HuevosIniciales")
                        .HasColumnType("integer")
                        .HasColumnName("huevos_iniciales");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int>("MachosIniciales")
                        .HasColumnType("integer")
                        .HasColumnName("machos_iniciales");

                    b.Property<string>("NucleoProduccionId")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nucleo_id");

                    b.Property<string>("TipoNido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_nido");

                    b.HasKey("Id")
                        .HasName("pk_produccion_lotes");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_produccion_lotes_lote_id");

                    b.HasIndex("NucleoProduccionId", "GranjaId")
                        .HasDatabaseName("ix_produccion_lotes_nucleo_id_granja_id");

                    b.ToTable("produccion_lotes", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Regional", b =>
                {
                    b.Property<int>("RegionalCia")
                        .HasColumnType("integer")
                        .HasColumnName("regional_cia");

                    b.Property<int>("RegionalId")
                        .HasColumnType("integer")
                        .HasColumnName("regional_id");

                    b.Property<string>("RegionalCodigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("regional_codigo");

                    b.Property<string>("RegionalEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("regional_estado");

                    b.Property<string>("RegionalNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("regional_nombre");

                    b.HasKey("RegionalCia", "RegionalId")
                        .HasName("pk_regionales");

                    b.ToTable("regionales", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.RoleCompany", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.HasKey("RoleId", "CompanyId")
                        .HasName("pk_role_companies");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_role_companies_company_id");

                    b.ToTable("role_companies", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.SeguimientoLoteLevante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ciclo");

                    b.Property<double>("ConsumoKgHembras")
                        .HasColumnType("double precision")
                        .HasColumnName("consumo_kg_hembras");

                    b.Property<int>("ErrorSexajeHembras")
                        .HasColumnType("integer")
                        .HasColumnName("error_sexaje_hembras");

                    b.Property<int>("ErrorSexajeMachos")
                        .HasColumnType("integer")
                        .HasColumnName("error_sexaje_machos");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<DateTime?>("FechaUltimoCambio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultimo_cambio");

                    b.Property<double?>("KcalAlH")
                        .HasColumnType("double precision")
                        .HasColumnName("kcal_alh");

                    b.Property<double?>("KcalAveH")
                        .HasColumnType("double precision")
                        .HasColumnName("kcal_aveh");

                    b.Property<string>("LoteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lote_id");

                    b.Property<int>("MortalidadHembras")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_hembras");

                    b.Property<int>("MortalidadMachos")
                        .HasColumnType("integer")
                        .HasColumnName("mortalidad_machos");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<double?>("ProtAlH")
                        .HasColumnType("double precision")
                        .HasColumnName("prot_alh");

                    b.Property<double?>("ProtAveH")
                        .HasColumnType("double precision")
                        .HasColumnName("prot_aveh");

                    b.Property<int>("SelH")
                        .HasColumnType("integer")
                        .HasColumnName("selh");

                    b.Property<int>("SelM")
                        .HasColumnType("integer")
                        .HasColumnName("selm");

                    b.Property<string>("TipoAlimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_alimento");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_seguimiento_lote_levante");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_seguimiento_lote_levante_lote_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_seguimiento_lote_levante_usuario_id");

                    b.ToTable("seguimiento_lote_levante", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Zona", b =>
                {
                    b.Property<int>("ZonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("zona_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZonaId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<int>("ZonaCia")
                        .HasColumnType("integer")
                        .HasColumnName("zona_cia");

                    b.Property<string>("ZonaEstado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zona_estado");

                    b.Property<string>("ZonaNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zona_nombre");

                    b.HasKey("ZonaId")
                        .HasName("pk_zonas");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_zonas_company_id");

                    b.ToTable("zonas", (string)null);
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Pais", "Pais")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departamentos_paises_pais_id");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Farm", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("Farms")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_farms_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Galpon", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_galpones_farms_granja_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Nucleo", "Nucleo")
                        .WithMany("Galpones")
                        .HasForeignKey("GalponNucleoId", "GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_galpones_nucleos_galpon_nucleo_id_granja_id");

                    b.Navigation("Farm");

                    b.Navigation("Nucleo");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Lote", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Farm", "Farm")
                        .WithMany("Lotes")
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lotes_farms_granja_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteGalpon", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Galpon", "Galpon")
                        .WithMany()
                        .HasForeignKey("GalponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lote_galpones_galpones_galpon_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.LoteReproductora", "LoteReproductora")
                        .WithMany("LoteGalpones")
                        .HasForeignKey("LoteId", "ReproductoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_galpones_lote_reproductoras_lote_id_reproductora_id");

                    b.Navigation("Galpon");

                    b.Navigation("LoteReproductora");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteReproductora", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Lote", "Lote")
                        .WithMany("Reproductoras")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_reproductoras_lotes_lote_id");

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteSeguimiento", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.LoteReproductora", "LoteReproductora")
                        .WithMany("LoteSeguimientos")
                        .HasForeignKey("LoteId", "ReproductoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lote_seguimientos_lote_reproductoras_lote_id_reproductora_id");

                    b.Navigation("LoteReproductora");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterListOption", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.MasterList", "MasterList")
                        .WithMany("Options")
                        .HasForeignKey("MasterListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_master_list_options_master_lists_master_list_id");

                    b.Navigation("MasterList");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_municipios_departamentos_departamento_id");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Nucleo", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Farm", "Farm")
                        .WithMany("Nucleos")
                        .HasForeignKey("GranjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nucleos_farms_granja_id");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionDiaria", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.ProduccionLote", "LoteProduccion")
                        .WithMany()
                        .HasForeignKey("LoteProduccionId")
                        .HasConstraintName("fk_produccion_diaria_produccion_lotes_lote_produccion_id");

                    b.Navigation("LoteProduccion");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.ProduccionLote", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produccion_lotes_lotes_lote_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Nucleo", "NucleoProduccion")
                        .WithMany()
                        .HasForeignKey("NucleoProduccionId", "GranjaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_produccion_lotes_nucleos_nucleo_id_granja_id");

                    b.Navigation("Lote");

                    b.Navigation("NucleoProduccion");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Regional", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("Regionales")
                        .HasForeignKey("RegionalCia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_regionales_companies_regional_cia");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.RoleCompany", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("RoleCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_companies_companies_company_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.Role", "Role")
                        .WithMany("RoleCompanies")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_companies_roles_role_id");

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.SeguimientoLoteLevante", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Lote", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seguimiento_lote_levante_lotes_lote_id");

                    b.HasOne("ZooSanMarino.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("fk_seguimiento_lote_levante_users_usuario_id");

                    b.Navigation("Lote");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Zona", b =>
                {
                    b.HasOne("ZooSanMarino.Domain.Entities.Company", "Company")
                        .WithMany("Zonas")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_zonas_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Company", b =>
                {
                    b.Navigation("Farms");

                    b.Navigation("Regionales");

                    b.Navigation("RoleCompanies");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Farm", b =>
                {
                    b.Navigation("Lotes");

                    b.Navigation("Nucleos");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Lote", b =>
                {
                    b.Navigation("Reproductoras");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.LoteReproductora", b =>
                {
                    b.Navigation("LoteGalpones");

                    b.Navigation("LoteSeguimientos");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.MasterList", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Nucleo", b =>
                {
                    b.Navigation("Galpones");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Pais", b =>
                {
                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("ZooSanMarino.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
