version: '3.8'

services:
  postgres-dev:
    image: postgres:15
    container_name: sanmarino-postgres-dev
    environment:
      POSTGRES_DB: sanmarinoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123456
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sanmarinoapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
