version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sanmarino-backend
    ports:
      - "5002:5002"          # API accesible en http://localhost:5002
    env_file:
      - .env                 # Usa tu .env (ver abajo)
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5002"
      PORT: "5002"
    # Sin dependencias de base de datos local (usando conexión remota)
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5002/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
