version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sanmarino-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: sanmarinoapp
    ports:
      - "5433:5432"          # Host:Contenedor
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sanmarinoapp || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sanmarino-backend
    ports:
      - "5002:5002"          # API accesible en http://localhost:5002
    env_file:
      - .env                 # Usa tu .env (ver abajo)
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5002"
      PORT: "5002"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5002/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
